### ISSUE TITLE
pytest not included in dependencies.

### ISSUE THREAD

**Issue by ryanwild7** [elphick/mass-composition#62]
pytest not included in dependencies or pytest included within non test code.

```
`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\XXXX\AppData\Local\pypoetry\Cache\virtualenvs\XXXX-o2Yat9EL-py3.9\lib\site-packages\xarray\tests\__init__.py", line 12, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
python-BaseException`
```

**Comment by elphick** [comment]
converted the comparison in the examples from:
```xarray.tests.assert_allclose()```
to:
```pd.testing.assert_frame_equal()```

This negated the need to ```import xarray.tests``` which had the pytest dependency.
